### ISSUE TITLE
Generated Code Emits CS1591

### ISSUE THREAD

**Issue by Documidas** [FaustVX/PrimaryParameter#8]
I'm trying to make use of this library in a project of mine where I have `<GenerateDocumentationFile>` set to true so that I can make use of IDE0005 (Remove unnecessary usings/imports) when building. However, I get a CS1591 (Missing XML comment for publicly visible type or member '[member]') warning for each primary constructor parameter I use `[Property]` on. This makes the library unusable if I also want to have warnings treated as errors.

Do you have any suggestions for how to fix this? The error is listed as being emitted in a `.g.cs` file produced by the source generator, but it's one that's only in memory as far as I can tell. For example, disabling CS1591 in `*.g.cs` files using a `.editorconfig` file doesn't have any effect. I've also tried a few different things with my XML comments to try and get C# to associate a comment with the generated properties, but so far I haven't been able to get anything to work.

This issue can be replicated with code like the following:
```cs
/// <summary>A class.</summary>
/// <param name="foo">A parameter.</param>
public sealed partial class Foobar(
    [Property] int foo
)
{
}
```

If it's possible for a source generator to read the XML comments, perhaps it's possible for the generator itself to create an XML comment using the `<param>` documentation for the primary constructor parameter? Unfortunately, I don't know how that would be done or how much work it would take to implement that. If there's an alternate solution that doesn't involve modifying the source generator, I'm very much open to that too.

**Comment by FaustVX** [comment]
I haven't though of that
I written it on the TODO list
Thanks for the idea.

I will take the simple way and add a `Summary` property in the attributes that will generate the `<summary>` tag on the member.

Currently, there is no way to generate documentation, as I use a Source Generator.
This library will generate in-memory source text that will then be compiled along with your source files.
So you can't edit these _files_.

I will try to take the time to implement that this weekend.

i will also add `#pragma warning disable` on top of the generated file to disable all kind of warning emitted in this file.

**Comment by Documidas** [comment]
Thank you so much for the quick reply! `#pragma warning disable` or even a dummy `<summary>` on the generated properties should be totally fine. I primarily use the `<GenerateDocumentationFile>` setting to make sure that I don't forget to write documentation for new parameters when refactoring, so it's not an issue if the "documentation" for the generated types doesn't exist.

This was the StackOverflow answer I had read that prompted me to mention the possibility of generating the XML documentation via the source generator itself:
https://stackoverflow.com/a/15768583

Unfortunately, I don't have any experience in this regard, so I can't comment on whether the example shown there is viable here.

**Comment by FaustVX** [comment]
In regard to SO, it could work, but I prefer to have a dedicated documentation for the generated members.
That way, you can have full control over the doc.
And a proper separation of doc with generated member & parameter.

**Comment by FaustVX** [comment]
Updated

It should be available in a few minutes on NuGet.

**Comment by FaustVX** [comment]
I've just pushed a new version (v1.4.0) to NuGet
Which don't emit the attributes on parameters in Release assemblies

It's not related to your issue, but I just wanted to inform you.
